blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('blog.views',
	url(r'^$', 'articles_all'),
	url(r'^(?P<article_id>\d+)/$', 'get_article'),
	url(r'^new/$', 'new_article'),
	url(r'^(?P<article_id>\d+)/delete/$', 'delete_article'),
	url(r'^(?P<article_id>\d+)/edit/$', 'edit_article'),
    )

game/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	url(r'^$', 'game.views.games'),
	url(r'^all/$', 'game.views.games'),
	url(r'^yourgames/$', 'game.views.yourgames'),
	url(r'^friends/$', 'game.views.friends_games'),
	url(r'^(?P<game_id>\d+)/$', 'game.views.game'),
	url(r'^new/$', 'game.views.new_game'),
	url(r'^(?P<game_id>\d+)/edit/$', 'game.views.edit_game'),
	url(r'^(?P<game_id>\d+)/favorite/$', 'game.views.favorite_game'),
	url(r'^(?P<game_id>\d+)/invite_user/$', 'game.views.invite_user'),
	url(r'^(?P<game_id>\d+)/remove/(?P<user_id>\d+)/$', 'game.views.remove_user'),
	url(r'^(?P<game_id>\d+)/delete/$', 'game.views.delete_game'),
	url(r'^(?P<game_id>\d+)/like/$', 'game.views.like_game'),
	url(r'^(?P<game_id>\d+)/unlike/$', 'game.views.unlike_game'),
	url(r'^(?P<game_id>\d+)/play/$', 'game.views.play_game'),
	url(r'^(?P<game_id>\d+)/new_comment/$', 'game.views.new_game_comment'),
	url(r'^(?P<game_id>\d+)/photos/$', 'game.views.all_photos'),
	url(r'^(?P<game_id>\d+)/photos/results/(?P<user_id>\d+)/item/(?P<item_id>\d+)/$', 'game.views.view_photo_from_all_photos'),
	url(r'^(?P<game_id>\d+)/comment/(?P<comment_id>\d+)/$', 'game.views.view_game_comment'),
	url(r'^(?P<game_id>\d+)/comment/(?P<comment_id>\d+)/edit/$', 'game.views.edit_game_comment'),
	url(r'^(?P<game_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', 'game.views.delete_game_comment'),
	url(r'^(?P<game_id>\d+)/comment/(?P<comment_id>\d+)/like/$', 'game.views.like_game_comment'),
	url(r'^(?P<game_id>\d+)/comment/(?P<comment_id>\d+)/unlike/$', 'game.views.unlike_game_comment'),
	url(r'^(?P<game_id>\d+)/results/$', 'game.views.game_results_all'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/$', 'game.views.view_player_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/edit/$', 'game.views.edit_player_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/delete/$', 'game.views.delete_player_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/like/$', 'game.views.like_player_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/unlike/$', 'game.views.unlike_player_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/new_comment/$', 'game.views.new_result_comment'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/disqualify/$', 'game.views.disqualify_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/$', 'game.views.view_result_comment'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/edit/$', 'game.views.edit_result_comment'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', 'game.views.delete_result_comment'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/like/$', 'game.views.like_result_comment'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/unlike/$', 'game.views.unlike_result_comment'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/item/(?P<item_id>\d+)/$', 'game.views.view_item_from_result'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/item/(?P<item_id>\d+)/like/$', 'game.views.like_result_item'),
	url(r'^(?P<game_id>\d+)/results/(?P<user_id>\d+)/item/(?P<item_id>\d+)/unlike/$', 'game.views.unlike_result_item'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/$', 'game.views.view_item_results'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/$', 'game.views.view_item_results'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/$', 'game.views.view_player_item'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/view/$', 'game.views.view_player_item'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/new_comment/$', 'game.views.new_result_item_comment'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/edit/$', 'game.views.edit_result_item_comment'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', 'game.views.delete_result_item_comment'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/like/$', 'game.views.like_result_item_comment'),
	url(r'^(?P<game_id>\d+)/item/(?P<item_id>\d+)/results/(?P<user_id>\d+)/comment/(?P<comment_id>\d+)/unlike/$', 'game.views.unlike_result_item_comment'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

thebesteye/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from thebesteye.forms import ContactForm1, ContactForm2, ContactForm3
from thebesteye.views import ContactWizard

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thebesteye.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'thebesteye.views.home'),
    (r'^games/', include('game.urls')),
    (r'^accounts/', include('allauth.urls')),
    (r'^accounts/', include('userprofile.urls')),
    (r'^lobby/', include('lobby.urls')),
    (r'^eyechat/', include('eyechat.urls')),
    (r'^sitemessages/', include('notification.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^activity/', include('activity.urls')),
    (r'^favorites/', include('favorite.urls')),
    (r'^leaderboards/', include('leaderboard.urls')),
    url(r'^contact/$', ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),
#    url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
#    url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
#    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
#    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # admin
    url(r'^admin/', include(admin.site.urls)),

    # user auth urls
#    url(r'^accounts/login/$', 'thebesteye.views.login'),
#    url(r'^accounts/auth/$', 'thebesteye.views.auth_view'),
#    url(r'^accounts/logout/$', 'thebesteye.views.logout'),
#    url(r'^accounts/loggedin/$', 'thebesteye.views.loggedin'),
#    url(r'^accounts/invalid/$', 'thebesteye.views.invalid'),
#    url(r'^accounts/register/$', 'thebesteye.views.register_user'),
#    url(r'^accounts/register_success/$', 'thebesteye.views.register_success'),
)

game/models.py
from django.db import models
from django.utils import timezone
from time import time
from django.contrib.auth.models import User
from PIL import Image
from PIL import _imaging
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import SmartResize, Transpose
from django.conf import settings
from django.core.files.storage import default_storage as storage

def get_upload_file_name(instance, filename):
	return settings.UPLOAD_FILE_PATTERN % (str(time()).replace('.','_'), filename)

# Create your models here.

class Game(models.Model):
	name 			= models.CharField(max_length=200, null=True, blank=True)
	description 	= models.TextField(null=True, blank=True)
	pubdate 		= models.DateTimeField(default=timezone.now)
	thumbnail 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	game_thumbnail 	= ProcessedImageField(
		upload_to=get_upload_file_name,
		processors=[
			Transpose(),
			SmartResize(200,200),
			],
		format = 'JPEG', 
		options={'quality': 60},
		null = True,
		blank = True
		)
	createdby 		 = models.ForeignKey(User, related_name='game_creator')
	lastedit 		 = models.DateTimeField(default=timezone.now)
	private_game 	 = models.BooleanField(default=False)
	private 		 = models.ManyToManyField(User, related_name='private_game_players')
	item01 			 = models.CharField(max_length=200, null=True, blank=True)
	item01photocount = models.IntegerField(default=0)
	item02 			 = models.CharField(max_length=200, null=True, blank=True)
	item02photocount = models.IntegerField(default=0)
	item03 			 = models.CharField(max_length=200, null=True, blank=True)
	item03photocount = models.IntegerField(default=0)
	item04 			 = models.CharField(max_length=200, null=True, blank=True)
	item04photocount = models.IntegerField(default=0)
	item05 			 = models.CharField(max_length=200, null=True, blank=True)
	item06 			 = models.CharField(max_length=200, null=True, blank=True)
	item07 			 = models.CharField(max_length=200, null=True, blank=True)
	item08 			 = models.CharField(max_length=200, null=True, blank=True)
	item09 			 = models.CharField(max_length=200, null=True, blank=True)
	item10 			 = models.CharField(max_length=200, null=True, blank=True)
	value			 = models.CharField(max_length=200, null=True, blank=True)
	endby_date		 = models.DateField(null=True, blank=True)
	game_closed		 = models.BooleanField(default=False)
	location		 = models.CharField(max_length=200, null=True, blank=True)
	gamelikes 		 = models.ManyToManyField(User, related_name='game_likes')
	photocount 		 = models.IntegerField(default=0)
	hide_latest		 = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

	def save(self):
		super(Game, self).save()
		if self.thumbnail:
			size = 200, 200
			image = Image.open(self.thumbnail)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.thumbnail.name, "w")
			format = 'png'  # You need to set the correct image format here
			image.save(fh, format)
			fh.close()
                
	def get_thumbnail(self):
		thumb = str(self.thumbnail)
		if not settings.DEBUG:
			thumb = thumb.replace('assets/', '')
			return thumb

		game_thumb = str(self.game_thumbnail)
		if not settings.DEBUG:
			game_thumb = game_thumb.replace('assets/', '')
			return game_thumb

class RandomGameItem(models.Model):
	item 	= models.CharField(max_length=200, null=True, blank=True)
	user 	= models.ForeignKey(User, related_name='suggestion_creator')
	pubdate	= models.DateTimeField(default=timezone.now)

	def __unicode__(self):
		return self.item

class GameComment(models.Model):
	game = models.ForeignKey(Game, related_name='game_for_comment')
	usertocomment = models.ForeignKey(User, related_name='game_comment')
	unique_id = models.IntegerField(default=1)
	comment = models.CharField(max_length=200, null=True, blank=True)
	pubdate = models.DateTimeField(default=timezone.now)
	lastedit = models.DateTimeField(default=timezone.now)
	gamecommentlikes = models.ManyToManyField(User, related_name='game_comment_likes')

	def __unicode__(self):
		return self.game.name

class Result(models.Model):
	game 			= models.ForeignKey(Game, related_name='game_host')
	player 			= models.ForeignKey(User, related_name='game_player')
	pubdate 		= models.DateTimeField(default=timezone.now)
	lastedit 		= models.DateTimeField(default=timezone.now)
	disqualified	= models.BooleanField(default=False)
	resultlikes 	= models.ManyToManyField(User, related_name='result_likes')
	location 		= models.CharField(max_length=200, null=True, blank=True)
	result01 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result01thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result01crop	= ProcessedImageField(
		upload_to=get_upload_file_name,
		processors=[
			Transpose(),
			SmartResize(1000,1000),
			],
		format = 'JPEG', 
		options={'quality': 90},
		null = True,
		blank = True
		)
	result01desc	= models.CharField(max_length=100, null=True, blank=True)
	result01likes 	= models.ManyToManyField(User, related_name='result_01_likes')
	result02 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result02thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result02crop	= ProcessedImageField(
		upload_to=get_upload_file_name,
		processors=[
			Transpose(),
			SmartResize(1000,1000),
			],
		format = 'JPEG', 
		options={'quality': 90},
		null = True,
		blank = True
		)
	result02desc	= models.CharField(max_length=100, null=True, blank=True)
	result02likes 	= models.ManyToManyField(User, related_name='result_02_likes')
	result03 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result03thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result03crop	= ProcessedImageField(
		upload_to=get_upload_file_name,
		processors=[
			Transpose(),
			SmartResize(1000,1000),
			],
		format = 'JPEG', 
		options={'quality': 90},
		null = True,
		blank = True
		)
	result03desc	= models.CharField(max_length=100, null=True, blank=True)
	result03likes 	= models.ManyToManyField(User, related_name='result_03_likes')
	result04 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result04thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result04crop	= ProcessedImageField(
		upload_to=get_upload_file_name,
		processors=[
			Transpose(),
			SmartResize(1000,1000),
			],
		format = 'JPEG', 
		options={'quality': 90},
		null = True,
		blank = True
		)
	result04desc	= models.CharField(max_length=100, null=True, blank=True)
	result04likes 	= models.ManyToManyField(User, related_name='result_04_likes')
	result05 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result05thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result05likes 	= models.ManyToManyField(User, related_name='result_05_likes')
	result06 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result06thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result06likes 	= models.ManyToManyField(User, related_name='result_06_likes')
	result07 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result07thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result07likes 	= models.ManyToManyField(User, related_name='result_07_likes')
	result08 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result08thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result08likes 	= models.ManyToManyField(User, related_name='result_08_likes')
	result09 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result09thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result09likes 	= models.ManyToManyField(User, related_name='result_09_likes')
	result10 		= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result10thumb	= models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	result10likes 	= models.ManyToManyField(User, related_name='result_10_likes')
	result_points	= models.IntegerField(default=1)
	gamewinner		= models.BooleanField(default=False)

	def __unicode__(self):
		return self.player.username

	def save(self):
		super(Result, self).save()
		if self.result01:
			size = 1667, 1250
			image = Image.open(self.result01)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.result01.name, "w")
			format = 'png'  # You need to set the correct image format here
			image.save(fh, format)
			fh.close()
		if self.result02:
			size = 1667, 1250
			image = Image.open(self.result02)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.result02.name, "w")
			format = 'png'  # You need to set the correct image format here
			image.save(fh, format)
			fh.close()
		if self.result03:
			size = 1667, 1250
			image = Image.open(self.result03)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.result03.name, "w")
			format = 'png'  # You need to set the correct image format here
			image.save(fh, format)
			fh.close()
		if self.result04:
			size = 1667, 1250
			image = Image.open(self.result04)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.result04.name, "w")
			format = 'png'  # You need to set the correct image format here
			image.save(fh, format)
			fh.close()
		if self.result05:
			size = 1667, 1250
			image = Image.open(self.result05)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.result05.name, "w")
			format = 'png'  # You need to set the correct image format here
			image.save(fh, format)
			fh.close()
		if self.result06:
			size = 1667, 1250
			image = Image.open(self.result06)
			image.thumbnail(size, Image.ANTIALIAS)
			fh = storage.open(self.result06.name, "w")

game/templates/edit_game_comment.html
{% extends "base.html" %}
{% block title %}The Best Eye: Edit Game Comment{% endblock %}
{% block extrahead %}
	<script type="text/javascript">
		function confirmDelete() {
			//display confirmation window which returns true or false
			if(!window.confirm("Are you sure you want to delete this comment?")) return false;
			 
			//user clicked 'OK'
			window.location.href="/games/{{game.id}}/comment/{{comment.unique_id}}/delete/"
			}
	</script>
{% endblock %}

{% block content %}

	<div id="whitebg">

		{% if comment %}
			<table width="100%" cellpadding="5">
				<tr>
					<td>
						<span class="heading16px">Edit Your Comment:</span>
					</td>
					<td align="right" style="padding-right:50px">
						<button onclick="confirmDelete();">Delete</button>
					</td>
				<tr>
					<td colspan="2">
						<b>{{game.createdby.username}}</b>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						{{game.description}}
					</td>
				</tr>
				<form action="/games/{{game.id}}/comment/{{comment.unique_id}}/edit/" method="post" />{% csrf_token %}
					<tr>
						<td colspan="2">
							{{form.comment}}
						</td>
					</tr>
					<tr>
						<td>
							<input type="submit" name="submit" value="Edit Comment" />
						</td>
						<td align="right" style="padding-right:15px">
							<a href="/games/{{game.id}}/">Back</a>
						</td>
					</tr>
				</form>
			</table>
		{% else %}
			<p>Nothing to show!</p>
			<p><a href="/games/"><b>Back to Games</b></a></p>
		{% endif %}

	</div>

{% endblock %}

game/templates/new_game.html
{% extends "base.html" %}
{% block title %}The Best Eye: New Game{% endblock %}
{% load static %}
{% block extrahead %}
	<script language="JavaScript" type="text/javascript" src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script language="JavaScript" type="text/javascript" src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link rel="stylesheet" href="{% static "assets/css/jquery-ui.css" %}">
	<script>
		$(function() {
			$( "#id_endby_date" ).datepicker();
		});
	</script>
	<script type="text/javascript">
		function getRandom01() {
			var randomchoices01 = [
				{% for randomitem in randomgameitems.all %}
					{% if forloop.last %}
						"{{randomitem.item}}"
					{% else %}
						"{{randomitem.item}}",
					{% endif %}
				{% endfor %}
			];
			document.getElementById("id_item01").value = randomchoices01[Math.floor(Math.random() * randomchoices01.length)];
		}
	</script>
	<script type="text/javascript">
		function getRandom02() {
			var randomchoices02 = [
				{% for randomitem in randomgameitems.all %}
					{% if forloop.last %}
						"{{randomitem.item}}"
					{% else %}
						"{{randomitem.item}}",
					{% endif %}
				{% endfor %}
			];
			document.getElementById("id_item02").value = randomchoices02[Math.floor(Math.random() * randomchoices02.length)];
		}
	</script>
	<script type="text/javascript">
		function getRandom03() {
			var randomchoices03 = [
				{% for randomitem in randomgameitems.all %}
					{% if forloop.last %}
						"{{randomitem.item}}"
					{% else %}
						"{{randomitem.item}}",
					{% endif %}
				{% endfor %}
			];
			document.getElementById("id_item03").value = randomchoices03[Math.floor(Math.random() * randomchoices03.length)];
		}
	</script>
	<script type="text/javascript">
		function getRandom04() {
			var randomchoices04 = [
				{% for randomitem in randomgameitems.all %}
					{% if forloop.last %}
						"{{randomitem.item}}"
					{% else %}
						"{{randomitem.item}}",
					{% endif %}
				{% endfor %}
			];
			document.getElementById("id_item04").value = randomchoices04[Math.floor(Math.random() * randomchoices04.length)];
		}
	</script>
	<script type="text/javascript">
		function checkInputExtension() {
			var filename = document.getElementById("id_game_thumbnail").value;
			if (filename == ''){
				alert('Please select an image');
				return false;
			}
			else {
				var extension = filename.substring(filename.lastIndexOf('.') + 1).toLowerCase();
				if(extension == "jpg" || extension == "png") {
					// filename is good to go
				}
				else {
					alert ("Please select a jpg or png");
					document.getElementById("id_game_thumbnail").value = '';
					return false;
				}
			}
		}
	</script>
	<script>
		function validateGame() {
			if (document.getElementById("id_item01").value == '' && document.getElementById("id_item02").value == '' && document.getElementById("id_item03").value == '' && document.getElementById("id_item04").value == '') {
				alert("You must enter some items for your game");
				return false;
			} else {
				return true;
			}
		}
	</script>
	<script type="text/javascript">
		function checkItem01() {
			var item01input = document.getElementById("id_item01").value;
			if (item01input == '') {
				alert('Please enter something for item 01');
				return false;
			}
		}
		function checkItem02() {
			var item02input = document.getElementById("id_item02").value;
			if (item02input == '') {
				alert('Please enter something for item 02');
				return false;
			}
		}
		function checkItem03() {
			var item03input = document.getElementById("id_item03").value;
			if (item03input == '') {
				alert('Please enter something for item 03');
				return false;
			}
		}
		function checkItem04() {
			var item04input = document.getElementById("id_item04").value;
			if (item04input == '') {
				alert('Please enter something for item 04');
				return false;
			}
		}
	</script>
{% endblock %}

{% block content %}

	<p>
		<div class="heading2">
			<img 
				class="heading_icon" 
				src="{% static "assets/images/newgame-pencil-256.png" %}" 
			/>
			Start a New Game:
		</div>
	</p>

	<div id="whitebg">

		<form action="/games/new/" method="post" enctype="multipart/form-data" onsubmit="return validateGame()" />{% csrf_token %}

			<table width="100%" cellpadding="5" bgcolor="#ffffff">
				<tr>
					<td width="200" rowspan="2">
						<img src="{% static "assets/images/thumbnail.png" %}" alt="Hi!" />
					</td>
					<td valign="top" width="130" align="right">
						Game Name: 
					</td>
					<td align="left" valign="top">
						{{form.name}}
					</td>
				<tr>
					<td align="right" valign="top">
						Description: 
					</td>
					<td align="left" valign="top">
						{{form.description}}
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<input type='file' id='id_game_thumbnail' name='game_thumbnail' onchange="checkInputExtension();" />
						<br />
					</td>
				</tr>
				<tr>
					<td colspan="3" style="padding-left:25px;">
						<img 
							width="30" 
							src="{% static "assets/images/game-camera-256.png" %}" 
						/> 
						<b>Items to Find:</b> 
						<input 
							type="button" 
							value="Random Game" 
							onclick="getRandom01(); getRandom02(); getRandom03(); getRandom04();" 
						/>
					</td>
				</tr>
				<tr>
					<td colspan="3" style="padding-left:45px;">
						<p>
							01: {{form.item01}} <input type="button" value="Random" onclick="getRandom01()" />
						</p>
						<p>
							02: {{form.item02}} <input type="button" value="Random" onclick="getRandom02()" />
						</p>
						<p>	
							03: {{form.item03}} <input type="button" value="Random" onclick="getRandom03()" />
						</p>
						<p>	
							04: {{form.item04}} <input type="button" value="Random" onclick="getRandom04()" /> 
							BONUS: Worth 3 points!
						</p>
					</td>
				</tr>

		<!--
				<tr>
					<td colspan="3">
						05: {{form.item05}}
					</td>
				</tr>
				<tr>
					<td colspan="3">
						06: {{form.item06}}
					</td>
				</tr>
				<tr>
					<td colspan="3">
						07: {{form.item07}}
					</td>
				</tr>
				<tr>
					<td colspan="3">
						08: {{form.item08}}
					</td>
				</tr>
				<tr>
					<td colspan="3">
						09: {{form.item09}}
					</td>
				</tr>
				<tr>
					<td colspan="3">
						10: {{form.item10}}
					</td>
				</tr> 
		-->

				<tr>
					<td colspan="3">
						<img 
							width="30" 
							src="{% static "assets/images/privategame-lock-256.png" %}" 
						/> 
						Private Game: {{form.private_game}} (Invite users from the game page)
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<img 
							width="30" 
							src="{% static "assets/images/enddate-hourglass-256.png" %}" 
						/> 
						End Date: {{form.endby_date}} (Leave blank to keep game open)
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<img 
							width="30" 
							src="{% static "assets/images/game-photo-256.png" %}" 
						/> 
						Hide Latest: {{form.hide_latest}} (Select to hide the latest images played)
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<p>
							<input type="submit" name="submit" value="New Game" />
						</p>
					</td>
				</tr>
			</table>
		</form>

	</div>

{% endblock %}