blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('blog.views',
	url(r'^$', 'articles_all'),
	url(r'^(?P<article_id>\d+)/$', 'get_article'),
	url(r'^new/$', 'new_article'),
	url(r'^(?P<article_id>\d+)/delete/$', 'delete_article'),
	url(r'^(?P<article_id>\d+)/edit/$', 'edit_article'),
    )

thebesteye/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from thebesteye.forms import ContactForm1, ContactForm2, ContactForm3
from thebesteye.views import ContactWizard

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thebesteye.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'thebesteye.views.home'),
    (r'^games/', include('game.urls')),
    (r'^accounts/', include('allauth.urls')),
    (r'^accounts/', include('userprofile.urls')),
    (r'^lobby/', include('lobby.urls')),
    (r'^eyechat/', include('eyechat.urls')),
    (r'^sitemessages/', include('notification.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^activity/', include('activity.urls')),
    (r'^favorites/', include('favorite.urls')),
    (r'^leaderboards/', include('leaderboard.urls')),
    url(r'^contact/$', ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),
#    url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
#    url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
#    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
#    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # admin
    url(r'^admin/', include(admin.site.urls)),

    # user auth urls
#    url(r'^accounts/login/$', 'thebesteye.views.login'),
#    url(r'^accounts/auth/$', 'thebesteye.views.auth_view'),
#    url(r'^accounts/logout/$', 'thebesteye.views.logout'),
#    url(r'^accounts/loggedin/$', 'thebesteye.views.loggedin'),
#    url(r'^accounts/invalid/$', 'thebesteye.views.invalid'),
#    url(r'^accounts/register/$', 'thebesteye.views.register_user'),
#    url(r'^accounts/register_success/$', 'thebesteye.views.register_success'),
)

userprofile/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
			url(r'^profile/$', 'userprofile.views.user_profile'),
			url(r'^profile/(?P<user_id>\d+)/$', 'userprofile.views.view_profile'),
			url(r'^profile/(?P<user_id>\d+)/games/$', 'userprofile.views.view_usergames'),
			url(r'^profile/(?P<user_id>\d+)/follow/$', 'lobby.views.follow_user'),
			url(r'^profile/(?P<user_id>\d+)/unfollow/$', 'lobby.views.unfollow_user'),
    	    url(r'^profile/(?P<user_id>\d+)/following/$', 'userprofile.views.following'),
        	url(r'^profile/(?P<user_id>\d+)/followers/$', 'userprofile.views.followers'),
	)

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from PIL import _imaging
from django.conf import settings
from django.core.files.storage import default_storage as storage
from django.utils import timezone
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import SmartResize, Transpose
from time import time
from game.models import Game, Achievement, Result

def get_upload_file_name(instance, filename):
	return settings.UPLOAD_FILE_PATTERN % (str(time()).replace('.','_'), filename)

# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User, related_name='user_object')
	visible = models.BooleanField(default=True)
	camera = models.CharField(max_length=100, null=True, blank=True)
	bio = models.TextField(null=True, blank=True)
	avatar = models.FileField(upload_to=get_upload_file_name, null=True, blank=True)
	avatar_thumbnail = ProcessedImageField(
		upload_to=get_upload_file_name,
		processors=[
			Transpose(),
			SmartResize(300,300),
			],
		format = 'JPEG', 
		options={'quality': 60},
		null = True,
		blank = True
		)
	totalpoints = models.IntegerField(default=1)
	following = models.ManyToManyField(User, related_name='following_list')
	birthday = models.DateField(null=True, blank=True)
	achievements = models.ManyToManyField(Achievement, related_name='achievements_list')
	blog_writer = models.BooleanField(default=False)
	favorite_games = models.ManyToManyField(Game, related_name='favorite_games')

# 	save this
#	def save(self, *args, **kwargs):
#		super(UserProfile, self).save(*args, **kwargs)
#		if self.avatar:
#			size = 200, 200
#			box = (100, 100, 400, 400)
#			image = Image.open(self.avatar)
#			cropit = image.crop(box)
#			image.paste(cropit, box)
#			image.thumbnail(size, Image.ANTIALIAS)
#			fh = storage.open(self.avatar.name, "w")
#			format = 'png'  # You need to set the correct image format here
#			image.crop(box).save(fh, format)
#			fh.close()
#		else:
#			image = None

	def __unicode__(self):
		return self.user.username

	def get_avatar(self):
		thumb = str(self.avatar)
		thumb = thumb.replace('assets/', '')

		return thumb

		thumbnail = str(self.avatar_thumbnail)
		thumbnail = thumbnail.replace('assets/', '')
		return thumbnail

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

userprofile/forms.py
from django import forms
from models import UserProfile

class UserProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ('avatar', 'visible', 'camera', 'bio', 'birthday', 'avatar_thumbnail')

userprofile/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from forms import UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.template import RequestContext
from PIL import Image
from PIL import _imaging
from django.core.files.storage import default_storage as storage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import Library
from models import UserProfile
from game.models import Game, Result
from notification.models import SiteMessage
from activity.models import Action

register = Library()


# Create your views here.

@login_required
def user_profile(request):
	thisuser = request.user
	if UserProfile.objects.filter(user=thisuser).exists():
		following = thisuser.user_object.following.count()
	else:
		following = 0
	followers = UserProfile.objects.filter(following=thisuser).count()
	s = SiteMessage.objects.filter(user=request.user, viewed=False).order_by('-pubdate')
	if request.method == 'POST':
		form = UserProfileForm(request.POST, request.FILES, instance=request.user.profile)
		if request.POST.get('ios_device'):
			ios_rotate = True
		else:
			ios_rotate = False
		if form.is_valid():
			f = form.save()
			return HttpResponseRedirect('/accounts/profile/')
		else:
			profile = UserProfile.objects.get(user=thisuser)

			return HttpResponseRedirect('/accounts/profile/')

	else:
		user = request.user
		profile = user.profile
		form = UserProfileForm(instance=profile)

	args = {'thisuser': thisuser, 'profile': profile, 'following': following, 'followers': followers, 's': s}
	args.update(csrf(request))

	args['form'] = form

	return render(request, 'profile.html', args)

def view_profile(request, user_id=1):
	if not request.user.is_authenticated():
		thisuser = None
		s = None
		following = None
		followers = None
	else:
		thisuser = request.user
		s = SiteMessage.objects.filter(user=request.user, viewed=False).order_by('-pubdate')
		following = thisuser.user_object.following.count()
		followers = followers = UserProfile.objects.filter(following=thisuser).count()
	
	if User.objects.filter(id=user_id).exists():
		userlookup = User.objects.get(id=user_id)
		viewprofile = userlookup.profile
	else:
		userlookup = None
		viewprofile = None

	if UserProfile.objects.filter(user=thisuser, following=userlookup).exists():
		iffollowing = 1
	else:
		iffollowing = None

	if UserProfile.objects.filter(user=userlookup, following=thisuser).exists():
		follower = True
	else:
		follower = False

	args = {'thisuser': thisuser, 'userlookup': userlookup, 'viewprofile': viewprofile, 'following': following, 'followers': followers, 'iffollowing': iffollowing, 's': s, 'follower': follower}
	args.update(csrf(request))

	return render(request, 'view_profile.html', args)

def view_usergames(request, user_id=1):
	if not request.user.is_authenticated():
		thisuser = None 
		s = None
		following = None
		followers = None
	else:
		thisuser = request.user 
		s = SiteMessage.objects.filter(user=request.user, viewed=False).order_by('-pubdate')
		following = thisuser.user_object.following.count()
		followers = UserProfile.objects.filter(following=thisuser).count()


	if User.objects.filter(id=user_id).exists():
		gamesuser = User.objects.get(id=user_id)
		gamesbyuser_list = Game.objects.filter(Q(createdby=gamesuser) | Q(game_host__player=gamesuser), Q(createdby=thisuser) | Q(private=thisuser) | Q(private_game=False)).order_by('-pubdate').distinct('pubdate')
	else:
		gamesuser = None
		gamesbyuser_list = None

	paginator = Paginator(gamesbyuser_list, 20)
	next = request.path

	page = request.GET.get('page')
	try:
		gamesbyuser = paginator.page(page)
	except PageNotAnInteger:
		gamesbyuser = paginator.page(1)
	except EmptyPage:
		gamesbyuser = paginator.page(paginator.num_pages)

	for game in gamesbyuser:
		game.played = Result.objects.filter(player=thisuser, game=game).exists()
		game.liked = Game.objects.filter(id=game.id, gamelikes=thisuser).exists()
		if Result.objects.filter(game=game).exists():
				game.latest = Result.objects.filter(game=game).order_by('-pubdate')[0]

	args = {'thisuser': thisuser, 'gamesuser': gamesuser, 'gamesbyuser': gamesbyuser, 'following': following, 'followers': followers, 's': s}
	return render(request, 'games_by_user.html', args)

@login_required
def following(request, user_id=1):
	thisuser = request.user
	userlookup = User.objects.get(id=user_id)
	if UserProfile.objects.filter(user=thisuser).exists():
		following_list = thisuser.user_object.following.all()
		following = thisuser.user_object.following.count()
	else:
		following = 0
		following_list = None
	followers = UserProfile.objects.filter(following=thisuser).count()
	s = SiteMessage.objects.filter(user=request.user, viewed=False).order_by('-pubdate')

	paginator = Paginator(following_list, 20)
	next = request.path

	page = request.GET.get('page')
	try:
		users_following = paginator.page(page)
	except PageNotAnInteger:
		users_following = paginator.page(1)
	except EmptyPage:
		users_following = paginator.page(paginator.num_pages)
	
	args = {'following': following, 'thisuser': thisuser, 'userlookup': userlookup, 'followers': followers, 's': s, 'users_following': users_following}
	args.update(csrf(request))

	return render(request, 'following.html', args)

@login_required
def followers(request, user_id=1):
	thisuser = request.user
	if UserProfile.objects.filter(user=thisuser).exists():
		following = thisuser.user_object.following.count()
		followers = UserProfile.objects.filter(following=request.user).count()
	else:
		following = 0
		followers = None
	s = SiteMessage.objects.filter(user=request.user, viewed=False).order_by('-pubdate')

	args = {'thisuser': thisuser, 'followers': followers, 'following': following, 's': s}
	args['followers_list'] = []
	args.update(csrf(request))

	followers_list = UserProfile.objects.filter(following=request.user)

	paginator = Paginator(followers_list, 20)
	next = request.path

	page = request.GET.get('page')
	try:
		user_followers = paginator.page(page)
	except PageNotAnInteger:
		user_followers = paginator.page(1)
	except EmptyPage:
		user_followers = paginator.page(paginator.num_pages)
	args['user_followers'] = user_followers

	for f in followers_list:
		user_status = (f, UserProfile.objects.filter(user=thisuser, following=f.user).exists())
		args['followers_list'].append(user_status)

	return render(request, 'followers.html', args)
	

userprofile/templates/games_by_user.html
{% extends "base.html" %}
{% block title %}The Best Eye: Player Games{% endblock %}
{% load static %}
{% load i18n %}
{% block extrahead %}
	<link rel="stylesheet" type="text/css" href="{% static "assets/css/all_games.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "assets/css/game.css" %}">
	<script>
		$(function() {
			$( document ).tooltip();
		});
	</script>
	<style>
		label {
			display: inline-block;
			width: 5em;
		}
	</style>
{% endblock %}

{% block content %}
	
	{% if gamesbyuser %}

		<p>
			<div class="heading16px">
				<a href="/accounts/profile/{{gamesuser.id}}/">
					{% if gamesuser.user_object.avatar_thumbnail %}
						<img src="{% get_static_prefix %}{{gamesuser.user_object.avatar_thumbnail}}" width="50">
					{% endif %} 
					<b>{{gamesuser.username}}</b>
				</a>'s games:
			</div>
		</p>

			{% for game in gamesbyuser %}
				<div class="gamecard_public">
					<!-- round profile pic area -->
					<div class="gctop gc">
					    <div class="profile_pic">
					    	<a href="/games/{{game.id}}/">
								<img 
									title="{{game.description|truncatewords:"20"}}" 
									class="p_pic" 
									src="{% get_static_prefix %}{{game.game_thumbnail}}" 
								/>
							</a>
					    </div>
					    <table><tr><td>
							<div class="game_name gc">
								<span>
									<a href="/games/{{game.id}}/" title="{{game.description|truncatewords:"20"}}">
										{{game.name}}
									</a>
								</span>
							</div>
							<div class="game_creator gc">
								<span>
									<p>
										Created by <a href="/accounts/profile/{{game.createdby.id}}/">@{{game.createdby.username}}</a> on {{game.pubdate}}
									</p>
									<p>
										{% if game.createdby == thisuser %}
											<b>
												<a href="/games/{{game.id}}/edit/"><b>Edit</b></a>
											</b>
										{% endif %}
									</p>
								</span>
							</div>
							<div class="game_stats">
								
								<span>

									{% if thisuser %}
												{% if game.liked %}
													<a href="/games/{{game.id}}/unlike/?next=/games/#{{game.id}}">
														<img 
															class="media_icon" 
															src="{% static "assets/images/heart-unlike-256.png" %}" 
															title="Unlike Game" 
														/> {{game.gamelikes.count}} 
													</a>
												{% else %}
													{% if game.gamelikes %}
														<a href="/games/{{game.id}}/like/?next=/games/#{{game.id}}">
															<img 
																class="media_icon" 
																src="{% static "assets/images/heart-like-256.png" %}" 
																title="Like Game" 
															/> {{game.gamelikes.count}} 
														</a>
													{% else %}
														<a href="/games/{{game.id}}/like/?next=/games/#{{game.id}}">
															<img 
																class="media_icon" 
																src="{% static "assets/images/heart-like-256.png" %}" 
																title="Like Game" 
															/> 
														</a>
													{% endif %}
												{% endif %}
											{% else %}
												{% if game.gamelikes %}
													<img 
														class="media_icon" 
														src="{% static "assets/images/heart-nolike-256.png" %}" 
														title="Like Game" 
													/> {{game.gamelikes.count}} 
												{% endif %}
											{% endif %}

											{% if game.game_host.count = 0 %}
												
											{% else %}
												<a href="/games/{{game.id}}/results/">
													<img 
														class="media_icon" 
														src="{% static "assets/images/friendgame-users-256.png" %}" 
														title="{{game.game_host.count}} Players"
													/> {{game.game_host.count}} 
												</a> 
											{% endif %}

											{% if game.photocount = 0 %}

											{% else %}
												<a href="/games/{{game.id}}/photos/">
													<img 
														class="media_icon"
														src="{% static "assets/images/game-photo-256.png" %}" 
														title="{{game.photocount}} Photos"
													/> {{game.photocount}} 
												</a> 
											{% endif %}

											{% if game.game_for_comment.count = 0 %}
												
											{% else %}
												<a href="/games/{{game.id}}/#comments">
													<img 
														class="media_icon" 
														src="{% static "assets/images/lobby-bubbles-256.png" %}" 
														title="{{game.game_for_comment.count}} Comments"
													/> {{game.game_for_comment.count}}
												</a>
											{% endif %}

									{% if game.private_game %}
										Private Game!
									{% endif %}

								</span>
							</div>
						</td></tr></table>

						{% if game.latest %}
							<table width="100%" cellpadding="5">
								<tr>
									<td colspan="4">
										<div class="heading3">
											<p>Latest Photos from <b>@{{game.latest.player.username}}</b>:</p>
										</div>
									</td>
								</tr>
								<tr>
									<td width="25%" align="center">
										{% if game.latest.result01crop %}
											<a href="/games/{{game.id}}/photos/">
												<img 
													title="{{game.latest.result01desc|truncatewords:"20"}}" 
													src="{% get_static_prefix %}{{game.latest.result01crop}}" 
													width="100"
												/>
											</a>
										{% else %}
											<img 
												src="{% static "assets/images/generic_avatar.png" %}" 
												alt="Hi!" 
												width="100" 
											/>
										{% endif %}
									</td>
									<td width="25%" align="center">
										{% if game.latest.result02crop %}
											<a href="/games/{{game.id}}/photos/">
												<img 
													title="{{game.latest.result02desc|truncatewords:"20"}}" 
													src="{% get_static_prefix %}{{game.latest.result02crop}}" 
													width="100"
												/>
											</a>
										{% else %}
											<img 
												src="{% static "assets/images/generic_avatar.png" %}" 
												alt="Hi!" 
												width="100" 
											/>
										{% endif %}
									</td>
									<td width="25%" align="center">
										{% if game.latest.result03crop %}
											<a href="/games/{{game.id}}/photos/">
												<img 
													title="{{game.latest.result03desc|truncatewords:"20"}}" 
													src="{% get_static_prefix %}{{game.latest.result03crop}}" 
													width="100"
												/>
											</a>
										{% else %}
											<img 
												src="{% static "assets/images/generic_avatar.png" %}" 
												alt="Hi!" 
												width="100" 
											/>
										{% endif %}
									</td>
									<td width="25%" align="center">
										{% if game.latest.result04crop %}
											<a href="/games/{{game.id}}/photos/">
												<img 
													title="{{game.latest.result04desc|truncatewords:"20"}}" 
													src="{% get_static_prefix %}{{game.latest.result04crop}}" 
													width="100"
												/>
											</a>
										{% else %}
											<img 
												src="{% static "assets/images/generic_avatar.png" %}" 
												alt="Hi!" 
												width="100" 
											/>
										{% endif %}
									</td>
								</tr>
							</table>
						{% endif %}
						
					</div>
					<div class="gcbottom"> 
						<!-- <span class="gcaccent gcactions"> -->
							{% if thisuser %}
								<div class="column">
									{% if game.played %}
										<a href="/games/{{game.id}}/results/{{thisuser.id}}/">Your Score</a>
									{% else %}
										{% if game.game_closed %}
											<a href="/games/{{game.id}}/results/">Game Over!</a>
										{% else %}
											<a href="/games/{{game.id}}/play/">Play</a>
										{% endif %}
									{% endif %}
								</div>

								<div class="inbetween_column">|</div> 

								<div class="column">
									{% if game.photocount = 0 %}
										No Photos!
									{% else %}
										<a href="/games/{{game.id}}/photos/">All Photos</a>
									{% endif %}
								</div>

								<div class="inbetween_column">|</div> 

								<div class="column">
									{% if game.photocount = 0 %}
										<a href="/games/{{game.id}}/" title="{{game.description|truncatewords:"20"}}">Moar</a>
									{% else %}
										<a href="/games/{{game.id}}/results/">Scoreboard</a>
									{% endif %}
								</div>

							{% else %}

								<div class="column">
									<a href="/accounts/login/">Play</a>
								</div>

								<div class="inbetween_column">|</div> 

								<div class="column">
									{% if game.photocount = 0 %}
										No Photos!
									{% else %}
										<a href="/games/{{game.id}}/photos/">All Photos</a>
									{% endif %}
								</div>

								<div class="inbetween_column">|</div> 
								
								<div class="column">
									{% if game.photocount = 0 %}
										<a href="/games/{{game.id}}/" title="{{game.description|truncatewords:"20"}}">Moar</a>
									{% else %}
										<a href="/games/{{game.id}}/results/">Scoreboard</a>
									{% endif %}
								</div>


							{% endif %} 
						<!-- </span> -->
					</div>
				</div>
				<br />
			{% endfor %}
			<div class="pagination" align="right">
				<span class="step-links">
					{% if gamesbyuser.has_previous %}
						<a href="?page={{ gamesbyuser.previous_page_number }}">previous</a>
					{% endif %}

					<span class="current">
						Page {{ gamesbyuser.number }} of {{ gamesbyuser.paginator.num_pages }}
					</span>

					{% if gamesbyuser.has_next %}
						<a href="?page={{ gamesbyuser.next_page_number }}">next</a>
					{% endif %}
				</span>
			</div>
	{% else %}
		<p><a href="/accounts/profile/{{gamesuser.id}}/"><b>{{gamesuser.username}}</b></a> doesn't have any games!</p>
	{% endif %}
{% endblock %}

userprofile/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}The Best Eye: Your Profile{% endblock %}
{% load i18n %}
{% block extrahead %}
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<script src="{% static "assets/js/jquery.guillotine.js" %}"></script>
	<script src="{% static "assets/js/modernizr.js" %}"></script>
	<script src="{% static "assets/js/modernizr-test.js" %}"></script>
	<!-- <script src="{% static "assets/js/user_profile.js" %}"></script> -->
	
	<link rel="stylesheet" href="{% static "assets/css/jquery-ui.css" %}">
	<link rel="stylesheet" href="{% static "assets/css/jquery.guillotine.css" %}">
	<link rel="stylesheet" href="{% static "assets/css/user_profile.css" %}">
	
	<script>
		$(function() {
		$( "#id_birthday" ).datepicker();
		});
	</script>
	<script type="text/javascript">
		function checkInputExtension() {
			var filename = document.getElementById("id_avatar_thumbnail").value;
			if (filename == ''){
				alert('Please select an image');
				return false;
			}
			else {
				var extension = filename.substring(filename.lastIndexOf('.') + 1).toLowerCase();
				if(extension == "jpg" || extension == "png") {
					// filename is good to go
				}
				else {
					alert ("Please select a jpg or png");
					document.getElementById("id_avatar_thumbnail").value = '';
					return false;
				}
			}
		}
	</script>
<!-- Hide until cropper
	<script type="text/javascript">

		function PreviewImage() {
			var oFReader = new FileReader();
			oFReader.readAsDataURL(document.getElementById("id_avatar_thumbnail").files[0]);

			oFReader.onload = function (oFREvent) {
				document.getElementById("avatar_preview").src = oFREvent.target.result;
				
			};

		};
		
	</script>
end hide until cropper -->
{% endblock %}

{% block content %}

	<div class="heading2">
		<img 
			class="heading_icon" 
			src="{% static "assets/images/profile-card-256.png" %}" 
		/> 
		Your Profile:
	</div>

	{% for field in form %}
		{{field.error}}

	{% endfor %}

	<form action="/accounts/profile/" method="post" enctype="multipart/form-data" />{% csrf_token %}
		<table width="100%" cellpadding="5" style="background:#ffffff;">
			<tr>
				<td width="50" align="right" style="padding-right:5px" valign="top">
					Avatar:
				</td>
			
				<td valign="top">					
					
					{% if profile.avatar_thumbnail %}
						<img src="{% get_static_prefix %}{{profile.avatar_thumbnail}}" width="200"><br />
					{% endif %}
					
					<input type='file' id='id_avatar_thumbnail' name='avatar_thumbnail' onchange="checkInputExtension();" /><br />

				</td>

			</tr>
			<tr>
				<td width="50" align="right" style="padding-right:5px" valign="top">
					Public:
				</td>
				<td valign="top">{{form.visible}}</td>
			</tr>
			<tr>
				<td align="right" style="padding-right:5px" valign="top">
					Bio:
				</td>
				<td valign="top">{{form.bio}}</td>
			</tr>
			<tr>
				<td align="right" style="padding-right:5px" valign="top">
					Camera:
				</td>
				<td valign="top">
					{{form.camera}} 
					<img 
						width="30" 
						src="{% static "assets/images/game-camera-256.png" %}" 
					/> 
				</td>
			</tr>
			<tr>
				<td align="right" style="padding-right:5px" valign="top">
					Birthday:
				</td>
				<td valign="top">
					{{form.birthday}} 
					<img 
						width="30" 
						src="{% static "assets/images/profile-calendar-256.png" %}" 
					/>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<input type="submit" value="Update" />
				</td>
			</tr>
		</table>
	</form>

{% endblock %}